import Head from 'next/head'
import Link from 'next/link'
import React from 'react'

export default function Layout({ title, children }) {
  return (
    <>
      <Head>
        <title>{title ? title + ' - NextSHop' : 'NextShop'} </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col justify-between">
        <header>
          <nav className="flex h-12 items-center px-4 justify-between shadow-md bg-slate-200">
            <Link href="/" className="text-1g front-bold">
              NextSHop
            </Link>
            <div>
              <Link href="cart" className="p-4">
                Cart
              </Link>
              <Link href="login" className="p-4">
                Login
              </Link>
              <Link href="info" className="p-4">
                Info
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-s px-4">{children}</main>
        <footer className="flex n-10 justify-center items-center shadow-inner bg-red-100">
          <p>Copyright &Copy; 2022 NextSHop</p>
        </footer>
      </div>
    </>
  )
}
